/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as layoutImport } from "./routes/__layout"
import { Route as layoutIndexImport } from "./routes/__layout/index"
import { Route as layoutRegisterImport } from "./routes/__layout/register"
import { Route as layoutOverviewImport } from "./routes/__layout/overview"

// Create/Update Routes

const layoutRoute = layoutImport.update({
    id: "/__layout",
    getParentRoute: () => rootRoute,
} as any)

const layoutIndexRoute = layoutIndexImport.update({
    path: "/",
    getParentRoute: () => layoutRoute,
} as any)

const layoutRegisterRoute = layoutRegisterImport.update({
    path: "/register",
    getParentRoute: () => layoutRoute,
} as any)

const layoutOverviewRoute = layoutOverviewImport.update({
    path: "/overview",
    getParentRoute: () => layoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/__layout": {
            preLoaderRoute: typeof layoutImport
            parentRoute: typeof rootRoute
        }
        "/__layout/overview": {
            preLoaderRoute: typeof layoutOverviewImport
            parentRoute: typeof layoutImport
        }
        "/__layout/register": {
            preLoaderRoute: typeof layoutRegisterImport
            parentRoute: typeof layoutImport
        }
        "/__layout/": {
            preLoaderRoute: typeof layoutIndexImport
            parentRoute: typeof layoutImport
        }
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
    layoutRoute.addChildren([layoutOverviewRoute, layoutRegisterRoute, layoutIndexRoute]),
])

/* prettier-ignore-end */
